In [1]:
import pandas as pd

ventas_df = pd.read_csv("../data/ventas.csv")
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [23]:
# CUENTA LOS VALORES DE LAS COLUMNAS FILTRADAS
ventas_df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [3]:
ventas_df[["vendedor", "producto", "categoria"]]

         vendedor     producto   categoria
0      Pedro Diaz  Auriculares  Accesorios
1      Luis Gomez   Monitor 27  Tecnologia
2     Carlos Vega   Silla Ergo  Mobiliario
3      Pedro Diaz   Laptop Pro  Tecnologia
4      Elena Mora  Auriculares  Accesorios
...           ...          ...         ...
1195   Luis Gomez   Raton Ergo  Accesorios
1196   Marta Ruiz   Laptop Pro  Tecnologia
1197   Ana Torres   Monitor 27  Tecnologia
1198   Ana Torres   Monitor 27  Tecnologia
1199   Marta Ruiz   Raton Ergo  Accesorios

[1200 rows x 3 columns]

### LOC - Localización por index

In [ ]:
### LOC: Localiza las filas por indice, etiquetas , dado que las columnas no tienen indice se debe usar su etiqueta o nombre

In [20]:
##m Muestra el rango de los indices
# ventas_df.loc [0: 4]
## Muestra el rango del indicio filtrando columnas
ventas_df.loc[0: 4, ["vendedor", "producto"]]

      vendedor     producto
0   Pedro Diaz  Auriculares
1   Luis Gomez   Monitor 27
2  Carlos Vega   Silla Ergo
3   Pedro Diaz   Laptop Pro
4   Elena Mora  Auriculares

In [7]:
# DEL INDEX 0 HASTA EL INDEX 1000
ventas_df.loc[:1000, ["vendedor", "producto"]]

         vendedor     producto
0      Pedro Diaz  Auriculares
1      Luis Gomez   Monitor 27
2     Carlos Vega   Silla Ergo
3      Pedro Diaz   Laptop Pro
4      Elena Mora  Auriculares
...           ...          ...
996   Carlos Vega   Laptop Pro
997   Javier Sanz   Laptop Pro
998    Marta Ruiz   Escritorio
999    Ana Torres   Laptop Pro
1000   Luis Gomez  Teclado Mec

[1001 rows x 2 columns]

In [8]:
# DEL INDEX 1000 HASTA EL FINAL
ventas_df.loc[1000:, ["vendedor", "producto"]]

        vendedor     producto
1000  Luis Gomez  Teclado Mec
1001  Luis Gomez  Teclado Mec
1002  Sofia Leon   Monitor 27
1003  Luis Gomez   Raton Ergo
1004  Luis Gomez   Laptop Pro
...          ...          ...
1195  Luis Gomez   Raton Ergo
1196  Marta Ruiz   Laptop Pro
1197  Ana Torres   Monitor 27
1198  Ana Torres   Monitor 27
1199  Marta Ruiz   Raton Ergo

[200 rows x 2 columns]

In [9]:
# DEVUELVE TODOS LOS INDEX
ventas_df.loc[:, ["vendedor", "producto"]]

         vendedor     producto
0      Pedro Diaz  Auriculares
1      Luis Gomez   Monitor 27
2     Carlos Vega   Silla Ergo
3      Pedro Diaz   Laptop Pro
4      Elena Mora  Auriculares
...           ...          ...
1195   Luis Gomez   Raton Ergo
1196   Marta Ruiz   Laptop Pro
1197   Ana Torres   Monitor 27
1198   Ana Torres   Monitor 27
1199   Marta Ruiz   Raton Ergo

[1200 rows x 2 columns]

### ILOC - SLICING SIMILAR A PYTHON NATIVO (EX. LISTAS)

In [ ]:
### TRABAJA COMO INDEXACION COMO PYTHON CON RANGOS DE FILAS Y COLUMNAS NUMERICAS QUE EMPIEZASN DE 0 A UN RANGO -1
ventas_df.iloc[0: 4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0

In [26]:
ventas_df.iloc[0: 4, 0: 3]

        fecha  region     vendedor
0  2024-01-02   Oeste   Pedro Diaz
1  2024-01-02     Sur   Luis Gomez
2  2024-01-02  Centro  Carlos Vega
3  2024-01-02  Centro   Pedro Diaz

### Sorting de columnas

In [28]:
ventas_df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [13]:
ventas_df["unidades"].min()

np.int64(1)

In [14]:
ventas_df["unidades"].max()

np.int64(14)

In [ ]:
# ORDENA POR ORDEN ASCENDENTE=TRUE O DESENDENTE=FALSE COLUMNA UNIDADES
ventas_df.sort_values(by="unidades", ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
54,2024-01-17,Norte,Luis Gomez,Silla Ergo,Mobiliario,1,280,0.00
491,2024-06-07,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,0.15
...,...,...,...,...,...,...,...,...
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.00
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.10
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.00
828,2024-09-12,Centro,Ana Torres,Raton Ergo,Accesorios,14,45,0.05
841,2024-09-16,Sur,Carlos Vega,Teclado Mec,Accesorios,14,95,0.00

In [16]:
ventas_df.sort_values(by="precio_unitario", ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1175,2024-12-22,Norte,Sofia Leon,Raton Ergo,Accesorios,7,45,0.15
891,2024-09-30,Sur,Javier Sanz,Raton Ergo,Accesorios,3,45,0.00
47,2024-01-16,Oeste,Carlos Vega,Raton Ergo,Accesorios,7,45,0.00
...,...,...,...,...,...,...,...,...
834,2024-09-13,Norte,Javier Sanz,Laptop Pro,Tecnologia,5,1200,0.00
848,2024-09-19,Norte,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
868,2024-09-24,Norte,Elena Mora,Laptop Pro,Tecnologia,6,1200,0.00
871,2024-09-25,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.05
875,2024-09-26,Centro,Javier Sanz,Laptop Pro,Tecnologia,8,1200,0.10

In [ ]:
# EJEMPLO PARA VER COMO ESTA MI DATA
ventas_df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [ ]:
# ORDENAR POR COLUMNAS
ventas_df.sort_values(by=["region", "unidades"], ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.00
70,2024-01-24,Centro,Luis Gomez,Auriculares,Accesorios,1,130,0.10
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320,NaN
...,...,...,...,...,...,...,...,...
1080,2024-11-26,Sur,Javier Sanz,Escritorio,Mobiliario,14,450,0.10
1081,2024-11-26,Sur,Marta Ruiz,Monitor 27,Tecnologia,14,320,0.05
1086,2024-11-28,Sur,Sofia Leon,Laptop Pro,Tecnologia,14,1200,0.15
1130,2024-12-09,Sur,Pedro Diaz,Teclado Mec,Accesorios,14,95,0.15
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00

In [ ]:
# MUESTRA LA INFORMACION DEL ARCHIVO ventas.csv EN DATAFRAME PARA SABER TIPOS DE VALORES SI HAY VASIOS
ventas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [39]:
# ORDENAR POR COLUMNAS PRIMERA COLUMNA POR ORDEN ASENDENTE Y SEGUNDA POR ORDEN DESENDENTE
ventas_df.sort_values(by=["region", "precio_unitario"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.00
40,2024-01-14,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200,0.10
156,2024-02-17,Centro,Pedro Diaz,Laptop Pro,Tecnologia,12,1200,0.05
...,...,...,...,...,...,...,...,...
918,2024-10-09,Sur,Carlos Vega,Raton Ergo,Accesorios,8,45,0.00
1034,2024-11-07,Sur,Javier Sanz,Raton Ergo,Accesorios,4,45,0.15
1058,2024-11-16,Sur,Marta Ruiz,Raton Ergo,Accesorios,2,45,0.10
1063,2024-11-19,Sur,Elena Mora,Raton Ergo,Accesorios,8,45,0.10
1096,2024-12-02,Sur,Javier Sanz,Raton Ergo,Accesorios,12,45,0.00

In [42]:
# VER INFORMACION DEL ARCHIVO POR FILTRADO DE COLUMNAS Y SOLO MUESTRA LAS 50 PRIMERAS LISTAS
ventas_df[["vendedor", "precio_unitario"]].value_counts().head(50)

vendedor     precio_unitario
Sofia Leon   280                27
Marta Ruiz   640                27
             320                27
Ana Torres   640                27
             320                26
Elena Mora   280                25
Sofia Leon   640                25
Pedro Diaz   130                24
Ana Torres   45                 24
Pedro Diaz   450                23
Luis Gomez   280                23
Pedro Diaz   280                23
Ana Torres   130                23
Marta Ruiz   450                22
Carlos Vega  95                 22
Marta Ruiz   95                 22
Ana Torres   280                21
Javier Sanz  130                21
             450                20
Sofia Leon   320                20
             130                20
Marta Ruiz   45                 20
Sofia Leon   1200               20
Pedro Diaz   1200               19
Elena Mora   130                19
Pedro Diaz   95                 19
Carlos Vega  130                19
Marta Ruiz   130                19
Elena Mora   45                 19
Luis Gomez   450                19
Marta Ruiz   280                19
Javier Sanz  280                19
Luis Gomez   320                18
             1200               18
Elena Mora   1200               18
Carlos Vega  280                17
Ana Torres   1200               17
Sofia Leon   45                 17
Pedro Diaz   320                17
Carlos Vega  320                17
Javier Sanz  1200               16
Carlos Vega  45                 16
Luis Gomez   640                16
Elena Mora   320                16
Javier Sanz  45                 16
             320                16
Sofia Leon   95                 15
Elena Mora   450                15
Luis Gomez   95                 15
Carlos Vega  640                15
Name: count, dtype: int64

In [ ]:
ventas_df.sort_values(by=["vendedor", "precio_unitario"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.00
108,2024-02-04,Sur,Ana Torres,Laptop Pro,Tecnologia,6,1200,0.00
129,2024-02-11,Norte,Ana Torres,Laptop Pro,Tecnologia,2,1200,0.05
169,2024-02-21,Centro,Ana Torres,Laptop Pro,Tecnologia,7,1200,0.00
345,2024-04-18,Sur,Ana Torres,Laptop Pro,Tecnologia,2,1200,0.05
...,...,...,...,...,...,...,...,...
203,2024-02-28,Norte,NaN,Raton Ergo,Accesorios,4,45,0.10
549,2024-06-20,Oeste,NaN,Raton Ergo,Accesorios,14,45,0.10
553,2024-06-22,Norte,NaN,Raton Ergo,Accesorios,7,45,0.05
639,2024-07-16,Norte,NaN,Raton Ergo,Accesorios,5,45,0.10
1032,2024-11-07,Oeste,NaN,Raton Ergo,Accesorios,9,45,0.00

In [ ]:
# SELECCIONA LA COLUMNA CON 5 DATOS CON MAS UNIDADES VENDIDAS
ventas_df.nlargest(5, ["unidades"])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.0
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.1
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.0
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.0

In [ ]:
# SELECCIONA LA COLUMNA CON 5 DATOS CON LAS MENOS UNIDADES VENDIDAS
ventas_df.nsmallest(5, ["unidades"])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.0
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.0