In [1]:
import pandas as pd

df = pd.read_csv("../data/clientes_sucio.csv")
df.head(15)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
4,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
10,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        12 non-null     str
 1   nombre       11 non-null     str
 2   ciudad       12 non-null     str
 3   fecha_nac    12 non-null     str
 4   gasto_total  9 non-null      str
 5   activo       12 non-null     str
 6   telefono     9 non-null      str
dtypes: str(7)
memory usage: 804.0 bytes

### Encontrar duplicados

In [3]:
filtro = df.duplicated()
df[filtro]

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
4,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
10,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN

In [4]:
# Elimina los duplicados siempre y cuando sea igual en todos los campos
clientes_sin_duplicados = df.drop_duplicates()
clientes_sin_duplicados.head(10)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [5]:
# Limpieza de datos renueva los espacios y ponen en minuscula la columna seleccionada
clientes_sin_duplicados["email"] = clientes_sin_duplicados["email"].str.strip().str.lower()

In [6]:
clientes_sin_duplicados.head(10)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [7]:
# title pone las primeras letras en mayusculas de las columnas selecionadas
clientes_sin_duplicados["nombre"] = clientes_sin_duplicados["nombre"].str.title().str.strip()
clientes_sin_duplicados["ciudad"] = clientes_sin_duplicados["ciudad"].str.title().str.strip()
clientes_sin_duplicados.head(10)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [8]:
### PREGUNTA DE LA CLASE PARA TRATAMIENTO DE CORREOS, AD-HOC A LA EMPRESA Y AL DOMINIO
'''
correo = "JAVIER.SANZ@mail.com" # asi es como te llega
lower_correo = "javier.sanz@mail.com" # Problema
esperado = "Javier.Sanz@mail.com"

splits = lower_correo.split("@")
nickname = splits[0].replace(".", " ").title().replace(" ", ".")
print(nickname + "@" + splits[1])
'''

'\ncorreo = "JAVIER.SANZ@mail.com" # asi es como te llega\nlower_correo = "javier.sanz@mail.com" # Problema\nesperado = "Javier.Sanz@mail.com"\n\nsplits = lower_correo.split("@")\nnickname = splits[0].replace(".", " ").title().replace(" ", ".")\nprint(nickname + "@" + splits[1])\n'

In [9]:
# DAR FORMATO Y LIMPIEZA A FORMATO FECHA
clientes_sin_duplicados["fecha_nac"] = pd.to_datetime(
    clientes_sin_duplicados["fecha_nac"],
    format="mixed"
)

clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [10]:
# VER INFORMACION DE TYPO DE FORMATO APLICADOS
clientes_sin_duplicados.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        10 non-null     str
 1   nombre       9 non-null      str
 2   ciudad       10 non-null     str
 3   fecha_nac    10 non-null     datetime64[us]
 4   gasto_total  7 non-null      str
 5   activo       10 non-null     str
 6   telefono     8 non-null      str
dtypes: datetime64[us](1), str(6)
memory usage: 640.0 bytes

In [11]:
### EQUIVALENTE A FUNCION LAMBDA
### DARLE TRATAMIENTO A UNA COLUMNA DE TEXTO PARA CONVERTIRLA A FORMATO NUMERICO Y PODER REALIZAR OPERACIONES
### USANDO MAP Y CASTEO A FLOAT64
def conversor_apunto_flotante(x: str) -> str:
    if x:
        return str(x).replace(".", "").replace(",", ".")
    return x

# CONVERTIR A FORMATO FLOAT
clientes_sin_duplicados["gasto_total"].map(conversor_apunto_flotante).astype("float64")

0     1250.50
1      890.00
2     2100.75
3         NaN
5     3400.00
6     1780.20
7         NaN
8     5600.00
9      430.10
11        NaN
Name: gasto_total, dtype: float64

In [12]:
### USANDO UNA FUNCIÓN ANÓNIMA O FUNCIÓN LAMBDA
# clientes_sin_duplicados["gasto_total"].map(lambda x: str(x).replace(".", "").replace(",", "."))

In [13]:
# CONVERTIR DE FORMATO STR A FLOAT YA QUE EN FORMATO STR NO SOPORTA OPERACIONES SOLO CONCATENA
# clientes_sin_duplicados["gasto_total"].map(conversor_apunto_flotante).astype("float64")

In [14]:
clientes_sin_duplicados["gasto_total"] = clientes_sin_duplicados["gasto_total"] \
    .str.replace(".", "") \
    .str.replace(",", ".").astype(pd.Float64Dtype())

In [15]:
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,1250.5,Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,890.0,si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,2100.75,SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,<NA>,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,3400.0,no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,1780.2,Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,<NA>,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,5600.0,si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,430.1,No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,<NA>,si,600654321

In [16]:
### FORMATO A VERDADERO O FALSO Y CONVERTIRLO A BOOL YA QUE DA MAS BENEFICIOS ESE FORMATO para no estar poniendo == "si"
clientes_sin_duplicados["activo"] = clientes_sin_duplicados["activo"].str.lower().str.replace(
    {"si":"1", "no": "0"}
).astype(int).astype(bool)

clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,1250.5,True,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,890.0,True,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,2100.75,True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,<NA>,False,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,3400.0,False,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,1780.2,True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,<NA>,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,5600.0,True,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,430.1,False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,<NA>,True,600654321

In [17]:
clientes_sin_duplicados.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        10 non-null     str
 1   nombre       9 non-null      str
 2   ciudad       10 non-null     str
 3   fecha_nac    10 non-null     datetime64[us]
 4   gasto_total  7 non-null      Float64
 5   activo       10 non-null     bool
 6   telefono     8 non-null      str
dtypes: Float64(1), bool(1), datetime64[us](1), str(4)
memory usage: 580.0 bytes

In [18]:
# DAR FORMATO CON REGEX A REEMPLAZAR QUITANDO EL +  Y ESPACIOS
clientes_sin_duplicados["telefono"] = clientes_sin_duplicados["telefono"].str.replace(r"\D", "", regex=True)
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-04-12,1250.5,True,34600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,890.0,True,600222333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-12-07,2100.75,True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,<NA>,False,600444555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,3400.0,False,34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,1780.2,True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-12-05,<NA>,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,5600.0,True,600999000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,430.1,False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,<NA>,True,600654321

In [19]:
clientes_sin_duplicados.to_csv("../data/clientes_limpios.csv", index=False)

In [20]:
pd.read_csv("../data/clientes_limpios.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        10 non-null     str
 1   nombre       9 non-null      str
 2   ciudad       10 non-null     str
 3   fecha_nac    10 non-null     str
 4   gasto_total  7 non-null      float64
 5   activo       10 non-null     bool
 6   telefono     8 non-null      float64
dtypes: bool(1), float64(2), str(4)
memory usage: 622.0 bytes

In [21]:
### Para guardar parquet se necesita la librería
# uv add pyarrow

In [24]:
clientes_sin_duplicados.to_parquet("../data/clientes_limpios.parquet.gzip", index=False, compression="gzip")

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

In [ ]:
#df = pd.read_parquet("../data/clientes_limpios.parquet.gzip")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        12 non-null     str
 1   nombre       11 non-null     str
 2   ciudad       12 non-null     str
 3   fecha_nac    12 non-null     str
 4   gasto_total  9 non-null      str
 5   activo       12 non-null     str
 6   telefono     9 non-null      str
dtypes: str(7)
memory usage: 804.0 bytes

### Comprobar la carga a BQ si parquet conserva la resolución de los datos texto (numérico)