# Práctica de Pandas — Palmer Penguins

**Dataset:** Palmer Penguins · Python / Pandas

Palmer Penguins es un dataset pequeño y apropiado para practicar limpieza, filtros, agregaciones y transformaciones con Pandas. El archivo contiene **344 registros y 8 columnas**.

- CSV directo: https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv
- Repositorio del proyecto: https://github.com/allisonhorst/palmerpenguins

**Instrucciones**
- Ejecuta las celdas en orden: varios ejercicios dependen de resultados anteriores (por ejemplo, `df` del ejercicio 1).
- Escribe tu código en la celda marcada con `# Escribe tu solución aquí` (puedes agregar más celdas).
- Intenta resolver cada ejercicio por tu cuenta antes de revisar el solucionario.

| Nivel | Preguntas | Conceptos principales |
|---|---|---|
| Básico | 1–10 | Carga, exploración, selección, estadísticas |
| Básico / Intermedio | 11–20 | Filtros, condiciones, ordenamiento, nulos |
| Intermedio | 21–29 | Nuevas columnas, groupby, agg, crosstab, transform, rank |
| Integrador | 30 | Transformación, agregación, análisis y exportación |

Código base recomendado:

```python
import pandas as pd

url = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv"
df = pd.read_csv(url)
```

---
## NIVEL 1 — BÁSICO
*Exploración y selección*

### 1. Carga del dataset

Carga el archivo `penguins.csv` utilizando Pandas y almacénalo en un DataFrame llamado `df`.

In [175]:
# Escribe tu solución aquí
import pandas as pd
url = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv"
df = pd.read_csv(url)

### 2. Primeros registros

Muestra las primeras 5 filas del dataset.

In [176]:
# Escribe tu solución aquí
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

### 3. Últimos registros

Muestra las últimas 8 filas del dataset.

In [177]:
# Escribe tu solución aquí
df.tail(8)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
336,Chinstrap,Dream,51.9,19.5,206.0,3950.0,male,2009
337,Chinstrap,Dream,46.8,16.5,189.0,3650.0,female,2009
338,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

### 4. Dimensiones

Determina el número de filas y el número de columnas del DataFrame.

In [178]:
# Escribe tu solución aquí
df.shape

(344, 8)

### 5. Columnas

Obtén una lista con los nombres de todas las columnas del DataFrame.

In [179]:
# Escribe tu solución aquí
list(df.columns)

['species',
 'island',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'sex',
 'year']

### 6. Tipos de datos

Muestra el tipo de dato (`dtype`) de cada columna.

In [180]:
# Escribe tu solución aquí
df.dtypes

species                  str
island                   str
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                      str
year                   int64
dtype: object

### 7. Información general

Utiliza una función de Pandas que permita visualizar las columnas, la cantidad de valores no nulos, los tipos de datos y la memoria utilizada.

In [181]:
# Escribe tu solución aquí
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 27.6 KB

### 8. Estadísticas descriptivas

Obtén las estadísticas descriptivas de todas las columnas numéricas.

In [182]:
# Escribe tu solución aquí
df. describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,342.000000,342.000000,342.000000,342.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,5.459584,1.974793,14.061714,801.954536,0.818356
min,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000

### 9. Selección de columnas

Crea un nuevo DataFrame llamado `penguins_mass` que contenga únicamente las columnas `species`, `island` y `body_mass_g`.

In [183]:
# Escribe tu solución aquí
penguins_mass = df[["species", "island", "body_mass_g"]]
penguins_mass

       species     island  body_mass_g
0       Adelie  Torgersen       3750.0
1       Adelie  Torgersen       3800.0
2       Adelie  Torgersen       3250.0
3       Adelie  Torgersen          NaN
4       Adelie  Torgersen       3450.0
..         ...        ...          ...
339  Chinstrap      Dream       4000.0
340  Chinstrap      Dream       3400.0
341  Chinstrap      Dream       3775.0
342  Chinstrap      Dream       4100.0
343  Chinstrap      Dream       3775.0

[344 rows x 3 columns]

### 10. Valores únicos

Determina cuáles son las especies diferentes existentes en `species` y cuántas especies distintas existen.

In [184]:
# Escribe tu solución aquí
df["species"].unique()

<ArrowStringArray>
['Adelie', 'Gentoo', 'Chinstrap']
Length: 3, dtype: str

---
## NIVEL 2 — BÁSICO / INTERMEDIO
*Filtros, ordenamiento y valores faltantes*

### 11. Conteo por especie

Cuenta cuántos pingüinos existen de cada especie.

In [185]:
# Escribe tu solución aquí
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

### 12. Conteo por isla

Determina cuántos pingüinos fueron registrados en cada isla.

In [186]:
# Escribe tu solución aquí
df["island"].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

### 13. Filtro simple

Obtén todos los pingüinos cuya masa corporal sea superior a 5000 gramos.

In [187]:
# Escribe tu solución aquí
filtro = df["body_mass_g"] > 5000
df[filtro]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [188]:
df[filtro]["body_mass_g"].min()

np.float64(5050.0)

### 14. Filtro por categoría

Obtén únicamente los pingüinos de especie Gentoo.

In [189]:
# Escribe tu solución aquí
filtro = df["species"] == "Gentoo"
df[filtro]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
152,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,female,2007
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
154,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,female,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
...,...,...,...,...,...,...,...,...
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009
272,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

### 15. Múltiples condiciones

Obtén los pingüinos que cumplan simultáneamente: `species == "Gentoo"` y `body_mass_g > 5000`.

In [190]:
# Escribe tu solución aquí
filtro = (df["species"] == "Gentoo") & (df["body_mass_g"] > 5000)
df[filtro]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

### 16. Condición OR

Obtén los registros correspondientes a pingüinos de las especies Adelie o Chinstrap. Intenta resolverlo sin crear dos DataFrames separados.

In [191]:
# Escribe tu solución aquí
filtro = df["species"].isin(["Adelie", "Chinstrap"])
df[filtro]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

### 17. Ordenamiento

Ordena el dataset de mayor a menor utilizando `body_mass_g`.

In [192]:
# Escribe tu solución aquí
df.sort_values(by="body_mass_g", ascending=False)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008
231,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,male,2008
...,...,...,...,...,...,...,...,...
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008
314,Chinstrap,Dream,46.9,16.6,192.0,2700.0,female,2008
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009

### 18. Top 10

Encuentra los 10 pingüinos con mayor masa corporal. Muestra solamente `species`, `island`, `sex` y `body_mass_g`.

In [193]:
# Escribe tu solución aquí
top10 = df.nlargest(10, "body_mass_g")[["species", "island", "sex", "body_mass_g"]]
top10

    species  island   sex  body_mass_g
169  Gentoo  Biscoe  male       6300.0
185  Gentoo  Biscoe  male       6050.0
229  Gentoo  Biscoe  male       6000.0
269  Gentoo  Biscoe  male       6000.0
231  Gentoo  Biscoe  male       5950.0
263  Gentoo  Biscoe  male       5950.0
165  Gentoo  Biscoe  male       5850.0
167  Gentoo  Biscoe  male       5850.0
267  Gentoo  Biscoe  male       5850.0
219  Gentoo  Biscoe  male       5800.0

### 19. Valores nulos

Determina cuántos valores faltantes existen en cada columna.

In [194]:
# Escribe tu solución aquí
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

### 20. Eliminar valores faltantes

Crea un DataFrame llamado `df_clean` que elimine únicamente los registros que tengan valores faltantes en `sex` o `body_mass_g`. Comprueba cuántas filas fueron eliminadas.

In [ ]:
# Escribe tu solución aquí
df_clean = df["sex"].isna() | df["body_mass_g"].isna()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN,2007
178,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN,2007
218,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN,2008
256,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN,2009
268,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN,2009
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009

In [223]:
df[df_clean].shape

(11, 8)

In [226]:
df_clean = df.dropna(subset=["sex", "body_mass_g"])
df_clean.info()

<class 'pandas.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    str
 1   island             333 non-null    str
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    str
 7   year               333 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 29.3 KB

---
## NIVEL 3 — INTERMEDIO
*Transformaciones, GroupBy y agregaciones*

### 21. Crear una nueva columna

Crea una columna llamada `body_mass_kg` con la masa corporal expresada en kilogramos. Recuerda: 1000 g = 1 kg. No modifiques `body_mass_g`.

In [230]:
# Escribe tu solución aquí
df["body_mass_kg"] = df["body_mass_g"] / 1000
df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.750
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.800
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.250
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.450
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,3.650
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,3.625
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,4.675
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,3.475
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,4.250

### 22. Clasificación mediante pd.cut()

Crea una nueva columna `mass_category` clasificando los pingüinos como **Light** si pesan menos de 3500 g, **Medium** si pesan entre 3500 y 4500 g (inclusive) y **Heavy** si pesan más de 4500 g. Utiliza `pd.cut()`.

In [ ]:
# Escribe tu solución aquí
df["mass_category"] = pd.cut(
    df["body_mass_g"],
    bins=[-float("inf"), 3500, 4500, float("inf")],
    labels=["Light", "Medium", "Heavy"]
)

In [ ]:
df[df["body_mass_g"] <= 3500]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,mass_category
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,Light
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,Light
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,Light
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007,Light
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,female,2007,Light
...,...,...,...,...,...,...,...,...,...
326,Chinstrap,Dream,48.1,16.4,199.0,3325.0,female,2009,Light
330,Chinstrap,Dream,42.5,17.3,187.0,3350.0,female,2009,Light
331,Chinstrap,Dream,52.2,18.8,197.0,3450.0,male,2009,Light
332,Chinstrap,Dream,45.2,16.6,191.0,3250.0,female,2009,Light
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,Light

### 23. Masa promedio por especie

Calcula la masa corporal promedio (`body_mass_g`) de cada especie. El resultado debe tener una fila por especie.

In [ ]:
# Escribe tu solución aquí

### 24. Múltiples estadísticas

Para cada especie calcula sobre `body_mass_g`: cantidad, promedio, mínimo, máximo y desviación estándar. Intenta resolverlo utilizando `groupby()` y `agg()`.

In [ ]:
# Escribe tu solución aquí

### 25. Agrupación utilizando dos columnas

Calcula la masa corporal promedio agrupando por `species` y `sex`. El resultado debe permitir comparar machos y hembras dentro de cada especie.

In [ ]:
# Escribe tu solución aquí

### 26. Tabla cruzada

Construye una tabla que muestre cuántos pingüinos existen para cada combinación `species` × `island`. Puedes utilizar `pd.crosstab()` o `pivot_table()`.

In [ ]:
# Escribe tu solución aquí

### 27. Pingüino más pesado de cada especie

Encuentra el registro correspondiente al pingüino con mayor `body_mass_g` dentro de cada especie. El resultado final debe mostrar `species`, `sex`, `island` y `body_mass_g`. No basta con mostrar únicamente la masa máxima: debes recuperar el registro completo correspondiente al máximo.

In [ ]:
# Escribe tu solución aquí

### 28. Diferencia respecto al promedio

Crea una columna `mass_difference` que indique cuánto pesa cada pingüino por encima o por debajo del promedio de su propia especie. Conceptualmente: *masa del pingüino − masa promedio de su especie*. Intenta resolverlo usando `groupby()` y `transform()`.

In [ ]:
# Escribe tu solución aquí

### 29. Ranking dentro de cada especie

Crea una columna `mass_rank` que indique el ranking de masa corporal de cada pingüino dentro de su propia especie. El pingüino más pesado debe tener `mass_rank = 1`. Luego muestra los 3 pingüinos más pesados de cada especie.

In [ ]:
df.head(20)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,mass_category
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,Medium
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,Medium
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,Light
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,Light
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,Medium
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,Medium
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,Heavy
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,Light
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,Medium
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007,Light
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007,Medium
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,female,2007,Light
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,male,2007,Medium
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007,Medium
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007,Medium
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,female,2007,Light
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,male,2007,Medium
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,female,2007,Light
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,male,2007,Medium

In [ ]:
# Escribe tu solución aquí
df["mass_rank"] = df.groupby("species")["body_mass_g"].rank(method="first", ascending=False)

In [ ]:
df[df["mass_rank"] <= 3].sort_values(["species", "mass_rank"])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,mass_category,mass_rank
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009,Heavy,1.0
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,male,2009,Heavy,2.0
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,male,2008,Heavy,3.0
313,Chinstrap,Dream,52.0,20.7,210.0,4800.0,male,2008,Heavy,1.0
305,Chinstrap,Dream,52.8,20.0,205.0,4550.0,male,2008,Heavy,2.0
315,Chinstrap,Dream,53.5,19.9,205.0,4500.0,male,2008,Medium,3.0
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007,Heavy,1.0
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007,Heavy,2.0
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008,Heavy,3.0

---
## EJERCICIO INTEGRADOR
*Aplicación de varias operaciones de Pandas*

### 30. Ejercicio integrador — Reporte de especies

Construye un DataFrame llamado `species_report` con una fila por especie y las columnas:

`species`, `total_penguins`, `average_body_mass`, `min_body_mass`, `max_body_mass`, `average_flipper_length` y `average_bill_length`.

1. Redondea los promedios a 2 decimales.
2. Ordénalo de mayor a menor por `average_body_mass`.
3. Identifica la especie con mayor masa promedio y la especie con mayor longitud promedio de aleta.
4. Guarda el resultado en `species_report.csv` sin incluir el índice.

In [ ]:
# Escribe tu solución aquí